// Generated by CoffeeScript 1.6.3
var Model, config, racer;

racer = require('racer');

Model = racer.Model;

config = {
  filename: __filename
};

module.exports = function(app, options) {
  Model.prototype.toast = function(type, msg) {
    return this.push("_page.toast." + type, msg);
  };
  app.fn('toast.remove', function(e, el) {
    var _ref, _ref1, _ref2;
    if ((app != null ? (_ref = app.model) != null ? (_ref1 = _ref.at(el)) != null ? (_ref2 = _ref1.path()) != null ? _ref2.substring(0, 12) : void 0 : void 0 : void 0 : void 0) === '_page.toast.') {
      return app.model.at(el).remove();
    }
  });
  return app.createLibrary(config, options);
};
