// Generated by CoffeeScript 1.6.3
var Model, config, racer;

racer = require('racer');

Model = racer.Model;

config = {
  filename: __filename
};

module.exports = function(app, options) {
  Model.prototype.toast = function(type, msg) {
    return this.push("_page.toast." + type, msg);
  };
  app.fn('toast.remove', function(e, el) {
    if (app.model.at(el).path().substring(0, 12) === '_page.toast.') {
      return app.model.at(el).remove();
    }
  });
  return app.createLibrary(config, options);
};
